### ISSUE TITLE
豆丁下载有水印

### ISSUE THREAD

**Issue by 1224161443** [you8023/downloadDocin#3]
您好，感谢大神的分享，今天我拿来用的时候下载下来有水印，不知道是不是我哪里没弄对还是怎么。和大神请教下。

**Comment by you8023** [comment]
这个水印是网站自己后台添加的，目前无法去除



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月4日(周六) 晚上9:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [you8023/downloadDocin] 豆丁下载有水印 (#3)




 
您好，感谢大神的分享，今天我拿来用的时候下载下来有水印，不知道是不是我哪里没弄对还是怎么。和大神请教下。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
